### ISSUE TITLE
Make into a module with a LICENSE?

### ISSUE THREAD

**Issue by pmlandwehr** [dssg/drain#21]
Hey-lo,

I've been periodically following `drain` development via github. It seems like it could get made into a first-class module with a license. (Dependent on having Drake, obviously.) That would be a cool, and a good preliminary for getting Drake onto [`conda-forge`](https://conda-forge.github.io/) and into other workflows...

**Comment by pmlandwehr** [comment]
... especially since `drain` itself seems much more active than `Drake`, which appears kind of dead.

**Comment by potash** [comment]
Thanks so much for the feedback! Currently swamped with DSSG stuff but will be packaging and licensing drain shortly-- by mid-September. We've got drain running two mature projects right now and expanding to a third so there's lots of features and documentation coming soon.

Regarding drake, I think it's not so much dead as stable!

**Comment by potash** [comment]
One month became eight but we finally have an MIT license, passing unit and integration tests via travis, and pip-installable via PyPI. More documentation and examples coming soon.
